---
- name: Gather distribution info
  setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check OS version and family
  assert:
      that: ansible_os_family == 'RedHat' and ansible_distribution_major_version is version_compare('7', '==')
      msg: "This role can only be run against RHEL/CENTOS 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always

- name: Check ansible version
  assert:
      that: ansible_version.full is version_compare(rhel7stig_min_ansible_version, '>=')
      msg: You must use Ansible {{ rhel7stig_min_ansible_version }} or greater
  tags:
      - always

- import_tasks: prelim.yml
  become: yes
  tags:
      - prelim_tasks

- name: Include CAT II patches
  import_tasks: fix-cat2.yml
  when: rhel7stig_cat2_patch | bool
  tags:
      - cat2
      - medium

